apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-factory.fullname" . }}
  labels:
    {{- include "ai-factory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ai-factory.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
