#!/usr/bin/env bash
set -euo pipefail

# Unified "create pull/merge request" entrypoint.
# Dispatches to the configured git provider adapter so the pipeline is no longer
# tied to GitLab. Supports gitlab | github | bitbucket.
#
# Inputs (env, with backward-compatible fallbacks):
#   TASK_ID          required (or $1)
#   GIT_PROVIDER     gitlab | github | bitbucket          (default: gitlab)
#   TARGET_BRANCH    base branch                          (default: main)
#   SOURCE_BRANCH    head branch                          (default: ai/<task>/final)
#   REPO_URL         clone URL (derives owner/repo path for github/bitbucket)
#   GIT_TOKEN        API token (falls back to <PROVIDER>_TOKEN)
#   PR_DRAFT         true | false                         (default: true; safety guardrail)
#   PR_LABEL         label applied to the PR/MR           (default: ai-generated)
#   PR_TITLE         title override                       (default: "AI Factory: <task>")
#   PR_BODY          body override
#
# Each provider script (providers/<provider>.sh) defines create_pull_request()
# and is sourced below. The created PR/MR JSON is written to /tmp/pr-<task>.json.

TASK_ID="${1:-${TASK_ID:?TASK_ID required}}"
GIT_PROVIDER="${GIT_PROVIDER:-gitlab}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"
SOURCE_BRANCH="${SOURCE_BRANCH:-ai/${TASK_ID}/final}"
PR_DRAFT="${PR_DRAFT:-true}"
PR_LABEL="${PR_LABEL:-ai-generated}"
PR_TITLE="${PR_TITLE:-AI Factory: ${TASK_ID}}"
PR_BODY="${PR_BODY:-Automated pull request generated by AI Factory for task ${TASK_ID}. Human review required before merge.}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVIDER_SCRIPT="${SCRIPT_DIR}/providers/${GIT_PROVIDER}.sh"

if [ ! -f "$PROVIDER_SCRIPT" ]; then
  echo "ERROR: unsupported GIT_PROVIDER='${GIT_PROVIDER}' (expected gitlab|github|bitbucket)" >&2
  exit 2
fi

# Derive "owner/repo" (or "workspace/repo") from REPO_URL for providers that
# need it. Handles https://host/owner/repo(.git) and git@host:owner/repo(.git).
git_repo_path() {
  local url="${1:-}"
  url="${url%.git}"
  url="${url#*://}"   # drop scheme://
  url="${url#*@}"     # drop user@
  url="${url/:/\/}"   # ssh "host:owner/repo" -> "host/owner/repo"
  url="${url#*/}"     # drop host
  echo "$url"
}
REPO_PATH="$(git_repo_path "${REPO_URL:-}")"

export TASK_ID GIT_PROVIDER TARGET_BRANCH SOURCE_BRANCH PR_DRAFT PR_LABEL PR_TITLE PR_BODY REPO_URL REPO_PATH

echo "Creating pull request via provider=${GIT_PROVIDER}: ${SOURCE_BRANCH} -> ${TARGET_BRANCH} (draft=${PR_DRAFT})"

# shellcheck source=/dev/null
source "$PROVIDER_SCRIPT"
create_pull_request
