#!/usr/bin/env bash
set -euo pipefail

# Unified "create pull/merge request" entrypoint.
# Dispatches to the configured git provider adapter so the pipeline is no longer
# tied to GitLab. Supports gitlab | github | bitbucket.
#
# Inputs (env, with backward-compatible fallbacks):
#   TASK_ID          required (or $1)
#   GIT_PROVIDER     gitlab | github | bitbucket          (default: gitlab)
#   TARGET_BRANCH    base branch                          (default: main)
#   SOURCE_BRANCH    head branch                          (default: ai/<task>/final)
#   REPO_URL         clone URL (derives owner/repo path for github/bitbucket)
#   GIT_TOKEN        API token (falls back to <PROVIDER>_TOKEN)
#   PR_DRAFT         true | false                         (default: true; safety guardrail)
#   PR_LABEL         label applied to the PR/MR           (default: ai-generated)
#   PR_TITLE         title override                       (default: "AI Factory: <task>")
#   PR_BODY          body override
#
# Each provider script (providers/<provider>.sh) defines create_pull_request()
# and is sourced below. The created PR/MR JSON is written to /tmp/pr-<task>.json.

TASK_ID="${1:-${TASK_ID:?TASK_ID required}}"
GIT_PROVIDER="${GIT_PROVIDER:-gitlab}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"
SOURCE_BRANCH="${SOURCE_BRANCH:-ai/${TASK_ID}/final}"
PR_DRAFT="${PR_DRAFT:-true}"
PR_LABEL="${PR_LABEL:-ai-generated}"
PR_TITLE="${PR_TITLE:-AI Factory: ${TASK_ID}}"
PR_BODY="${PR_BODY:-Automated pull request generated by AI Factory for task ${TASK_ID}. Human review required before merge.}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVIDER_SCRIPT="${SCRIPT_DIR}/providers/${GIT_PROVIDER}.sh"

if [ ! -f "$PROVIDER_SCRIPT" ]; then
  echo "ERROR: unsupported GIT_PROVIDER='${GIT_PROVIDER}' (expected gitlab|github|bitbucket)" >&2
  exit 2
fi

# Derive "owner/repo" (or "workspace/repo") from REPO_URL for providers that
# need it. Handles https://host/owner/repo(.git) and git@host:owner/repo(.git).
git_repo_path() {
  local url="${1:-}"
  url="${url%.git}"
  url="${url#*://}"   # drop scheme://
  url="${url#*@}"     # drop user@
  url="${url/:/\/}"   # ssh "host:owner/repo" -> "host/owner/repo"
  url="${url#*/}"     # drop host
  echo "$url"
}
REPO_PATH="$(git_repo_path "${REPO_URL:-}")"

# Redact any secret that slipped into the PR title/body (e.g. an operator-set
# PR_BODY, or an AI-authored summary) before it is sent to the provider and
# becomes a permanent, world-readable part of the PR.
aif_redact() {
  # Mirrors gateway TaskService.redactSecrets: provider token shapes,
  # user:secret@host URLs, secret-ish key=value / key: value assignments
  # (token/secret/password/passwd/pwd/api_key/access_key/private_key/credential),
  # Authorization|auth headers, and Bearer/Basic tokens. Case-insensitive keyword
  # matching is spelled out with explicit classes so it works on both GNU and BSD
  # sed (no GNU-only `I` flag).
  # NOTE: the Java AWS_SECRET_BARE rule (a context-free 40-char base64 secret) is
  # intentionally NOT mirrored here — pinning "exactly 40 AND contains +/" needs
  # lookahead that POSIX ERE lacks, and a looser rule would mangle file paths and
  # commit SHAs common in PR bodies. The contextual aws_*_key= form is covered by
  # the assignment rule above.
  printf '%s' "${1:-}" | sed -E \
    -e 's#([a-zA-Z][a-zA-Z0-9+.-]*://)[^/[:space:]:@]+:[^/[:space:]@]+@#\1<redacted>@#g' \
    -e 's#gh[posru]_[A-Za-z0-9]{16,}#<redacted>#g' \
    -e 's#glpat-[A-Za-z0-9_-]{16,}#<redacted>#g' \
    -e 's#xox[baprs]-[A-Za-z0-9-]{10,}#<redacted>#g' \
    -e 's#AKIA[0-9A-Z]{16}#<redacted>#g' \
    -e 's#sk-[A-Za-z0-9]{20,}#<redacted>#g' \
    -e 's#AIza[0-9A-Za-z_-]{20,}#<redacted>#g' \
    -e 's#([A-Za-z0-9_-]*([Tt][Oo][Kk][Ee][Nn]|[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Pp][Aa][Ss][Ss][Ww][Dd]|[Pp][Ww][Dd]|[Aa][Pp][Ii][_-]?[Kk][Ee][Yy]|[Aa][Cc][Cc][Ee][Ss][Ss][_-]?[Kk][Ee][Yy]|[Pp][Rr][Ii][Vv][Aa][Tt][Ee][_-]?[Kk][Ee][Yy]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll])[A-Za-z0-9_-]*[[:space:]]*[:=][[:space:]]*)([Bb]earer[[:space:]]+|[Bb]asic[[:space:]]+)?[^[:space:]]+#\1<redacted>#g' \
    -e 's#(^|[^A-Za-z0-9_])([Aa][Uu][Tt][Hh]([Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn])?[[:space:]]*[:=][[:space:]]*).+#\1\2<redacted>#g' \
    -e 's#([Bb]earer|[Bb]asic)[[:space:]]+[A-Za-z0-9._+/=-]{8,}#\1 <redacted>#g'
}
PR_TITLE="$(aif_redact "$PR_TITLE")"
PR_BODY="$(aif_redact "$PR_BODY")"

export TASK_ID GIT_PROVIDER TARGET_BRANCH SOURCE_BRANCH PR_DRAFT PR_LABEL PR_TITLE PR_BODY REPO_URL REPO_PATH

echo "Creating pull request via provider=${GIT_PROVIDER}: ${SOURCE_BRANCH} -> ${TARGET_BRANCH} (draft=${PR_DRAFT})"

# shellcheck source=/dev/null
source "$PROVIDER_SCRIPT"
create_pull_request
